package database

import (
	"fmt"
	"log"

	"github.com/mmirzaei559/taskmanager/models"
)

func GetAllTasks() ([]models.Task, error) {
	rows, err := DB.Query("SELECT id, title, description, completed, created_at, client_ip FROM tasks")
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var tasks []models.Task
	for rows.Next() {
		var task models.Task
		err := rows.Scan(&task.ID, &task.Title, &task.Description, &task.Completed, &task.CreatedAt)
		if err != nil {
			log.Printf("Error scanning task: %v", err)
			continue
		}
		tasks = append(tasks, task)
	}

	return tasks, nil
}

func CreateTask(title, description, clientIP string) (int64, error) {
	result, err := DB.Exec(
		"INSERT INTO tasks (title, description, client_ip) VALUES (?, ?, ?)",
		title, description, clientIP,
	)

	id, err := result.LastInsertId()
	if err != nil {
		return 0, err
	}

	return id, nil
}

func UpdateTaskStatus(id int, completed bool) error {
	_, err := DB.Exec("UPDATE tasks SET completed = ? WHERE id = ?", completed, id)
	return err
}

// Benchmark function
func BenchmarkTasks(count int, clientIP string) error {
	// Start transaction
	tx, err := DB.Begin()
	if err != nil {
		return err
	}

	// Prepare statement
	stmt, err := tx.Prepare(`
        INSERT INTO tasks (title, description, client_ip) 
        VALUES (?, ?, ?)
    `)
	if err != nil {
		tx.Rollback()
		return err
	}
	defer stmt.Close()

	for i := 0; i < count; i++ {
		title := fmt.Sprintf("Benchmark Task %d", i)
		description := fmt.Sprintf("Generated by benchmark from IP %s", clientIP)
		_, err := stmt.Exec(title, description, clientIP)
		if err != nil {
			tx.Rollback()
			return err
		}
	}

	return tx.Commit()
}
